name: eeg_deployment
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.15.3
  - blas=1.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - expat=2.7.4
  - ld_impl_linux-aarch64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libopenblas=0.3.31
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.4.2
  - numpy-base=2.4.2
  - openblas=0.3.31
  - openssl=3.6.1
  - packaging=25.0
  - pip=26.0.1
  - portaudio=19.7.0
  - pthread-stubs=0.3
  - python=3.11.14
  - python-sounddevice=0.5.2
  - python_abi=3.11
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - cffi==2.0.0
      - pycparser==3.0
      - sounddevice==0.5.5
prefix: /home/sscs/miniconda3/envs/eeg_deployment
